---
:ems:
  :ems_nsxt:
    :blacklisted_event_names: []
    :event_handling:
      :event_groups:
:ems_refresh:
  :nsxt:
    :inventory_object_refresh: true
    :allow_targeted_refresh: true
    :refresh_interval: 4.hours
:http_proxy:
  :nsxt:
    :host:
    :password:
    :port:
    :user:
:log:
  :level_nsxt: info
:workers:
  :ems_refresh_worker_nsxt_network:
    :inherits_from: ems_refresh_worker
  :event_catcher_nsxt_network:
    :inherits_from: event_catcher
    :poll: 20.seconds
